### PR TITLE
Removed unnecessary json deserialization

### PR DESCRIPTION
**Pull request by bismitpanda**
Removed the dependency of `serde_json` as well JSON deserialization.

### CODE REVIEW

**Comment by Axlefublr** [comment]
omg thank you for going into so much trouble!

however by the time I noticed this, I already rewrote, like, the entire app

**Comment by bismitpanda** [comment]
Just want to ask, is the json deserialization necessary? It adds the parsing overhead

You can try
```rust
use std::io::BufRead;

let bytes = include_bytes!("words.txt"); // The `words.txt` file would contain one word on each line
let lines: Vec<&str> = bytes.lines().collect();
```

**Comment by Axlefublr** [comment]
I tried using a normal txt file, but it can potentially have different line endings on different os's, but with json that's no longer a problem. however I haven't tried this suggested solution, thank you! will try it out

**Comment by Axlefublr** [comment]
Two things I want to ask due to my inexperience:

1. Why are you using include_bytes! over include_str! in this case?
2. If you create an iterator of lines, wouldn't that contain line endings?

The reason I'm using json is so that no matter what line endings (\r\n or \n) the file has (in case it was changed for some reason (maybe automatically by some editor)), the words are going to be processed correctly.

And since I want to join the words by spaces rather than newlines, I would have to trim the newlines, but I'm not sure if .trim() would include the potential \r (authotkey infamously forgets about that one, so you have to do your own regex)

**Comment by bismitpanda** [comment]
1. I am using `include_bytes!()` as `&[u8]` implements `BufRead` whereas `&str` does not. (Here, there is a minor change. `lines()` returns an iterator of `Result<String, io::Error>` instead of `String`)
So, it should be
```rust
use std::io::{BufRead, Error};

let bytes = include_bytes!("words.txt"); // The `words.txt` file would contain one word on each line
let lines: Result<Vec<String>, Error>  = bytes.lines().collect();
if let Ok(lines) = lines {
    // Your logic
} else {
    // Say to user that parsing failed.
}
```

2. No, it would not, from the `BufRead::lines()` [doc](https://doc.rust-lang.org/std/io/trait.BufRead.html#method.lines)
> Each string returned will not have a newline byte (the 0xA byte) or CRLF (0xD, 0xA bytes) at the end.

**Comment by Axlefublr** [comment]
1. Thank you for the elaboration! Makes sense, I wouldn't expect parsing to be an infallible operation lol
2. Oh wow! That's incredibly useful then: usually in other languages line endings would be included in an iterator like this, I'll most likely use your solution then!

**Pull request closed without merging**
